[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FourierFlows = "2aec4490-903f-5c70-9b11-9bed06a700e1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
QGDipoles = "192f05a4-068c-458e-9e9e-a50cd96b7215"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
